# Generated by Django 3.1.4 on 2022-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db_models', '0023_auto_20220225_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolinfo',
            name='logo',
            field=models.URLField(default='', verbose_name='logo url'),
        ),
    ]
