# Generated by Django 3.1.4 on 2023-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db_models', '0031_auto_20230921_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterinfo',
            name='cluster_service_name',
            field=models.CharField(blank=True, help_text='集群所属服务', max_length=128, null=True, verbose_name='集群所属服务'),
        ),
    ]
