# Generated by Django 3.1.4 on 2023-04-27 09:38

import db_models.models.host
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0032_auto_20230316_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectLogRuleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_instance_name', models.CharField(help_text='服务实例名称', max_length=64, verbose_name='服务实例名称')),
                ('operation_uuid', models.CharField(help_text='采集uuid', max_length=36, verbose_name='采集uuid')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='发生时间', null=True, verbose_name='发生时间')),
                ('status', models.IntegerField(choices=[(2, '采集中'), (0, '录入成功'), (1, '采集失败'), (3, '数据重复'), (4, '数据不一致'), (5, '文件不存在或无需配置规则')], default=2, help_text='采集状态', verbose_name='采集状态')),
                ('result', models.CharField(default='', help_text='提示信息', max_length=1024, verbose_name='提示信息')),
            ],
            options={
                'verbose_name': '服务日志清理规则采集记录',
                'verbose_name_plural': '服务日志清理规则采集记录',
                'db_table': 'omp_collect_log_history',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='crontab_detail',
            field=models.JSONField(default=db_models.models.host.default_crontab_detail, max_length=512, verbose_name='定时任务详情'),
        ),
        migrations.CreateModel(
            name='ClearLogRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_instance_name', models.CharField(help_text='服务实例名称', max_length=64, verbose_name='服务实例名称')),
                ('switch', models.IntegerField(choices=[(1, '开启'), (0, '关闭')], default=0, help_text='清理状态', verbose_name='清理状态')),
                ('md5', models.CharField(help_text='md5码', max_length=64, verbose_name='md5码')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='发生时间', null=True, verbose_name='发生时间')),
                ('exec_dir', models.CharField(help_text='执行路径', max_length=512, verbose_name='执行路径')),
                ('exec_type', models.CharField(help_text='规则类型', max_length=64, verbose_name='规则类型')),
                ('exec_value', models.IntegerField(default=0, help_text='策略值', verbose_name='策略值')),
                ('exec_rule', models.CharField(help_text='通配规则', max_length=64, verbose_name='通配规则')),
                ('host', models.ForeignKey(help_text='主机', on_delete=django.db.models.deletion.CASCADE, to='db_models.host')),
            ],
            options={
                'verbose_name': '服务日志清理规则',
                'verbose_name_plural': '服务日志清理规则',
                'db_table': 'omp_clear_log_rule',
            },
        ),
    ]