# Generated by Django 3.1.4 on 2023-05-11 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0033_auto_20230420_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationhub',
            name='deploy_mode',
            field=models.JSONField(blank=True, help_text='部署模式', null=True, verbose_name='部署模式'),
        ),
        migrations.AddField(
            model_name='product',
            name='deploy_mode',
            field=models.CharField(blank=True, help_text='部署模式', max_length=128, null=True, verbose_name='部署模式'),
        ),
        migrations.AddField(
            model_name='service',
            name='deploy_mode',
            field=models.CharField(blank=True, help_text='部署模式', max_length=128, null=True, verbose_name='部署模式'),
        ),

    ]