# Generated by Django 3.1.4 on 2023-11-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0035_auto_20230524_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('modified', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('alert_type', models.IntegerField(choices=[(1, 'feishu'), (2, 'doem'), (0, 'douc')], default=0, help_text='告警类别', verbose_name='告警类别')),
                ('switch', models.IntegerField(choices=[(0, '关闭'), (1, '开启')], default=0, help_text='开关', verbose_name='开关')),
                ('alert_setting', models.JSONField(help_text='推送告警配置', verbose_name='推送告警配置')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='serviceconfhistory',
            name='change_value',
            field=models.CharField(default='', help_text='修改值', max_length=512, verbose_name='修改值'),
        ),
        migrations.AlterField(
            model_name='backupcustom',
            name='notes',
            field=models.CharField(default='', max_length=128, verbose_name='备注'),
        ),
    ]